package com.political.expansion2.ranged;

import net.minecraft.ChatFormatting;

/**
 * Phase-2 spell catalogue — 88 unique RIGHT CLICK casts for {@code arc2_} weapons.
 * Behaviour is executed by {@link RangedAbilityEngine2} from {@link CastPattern} + {@link CastEffects}.
 */
public enum RangedCast2 {
    SOLAR_BEAM("Solar Beam", "Lance the sun into a single foe, igniting them with stellar fire.",
            32, 4, 14f, 28, ChatFormatting.GOLD,
            CastPattern.BEAM, CastEffects.of(ParticleKind.FLAME, 140, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    INFERNO_NOVA("Inferno Nova", "Detonate a ring of hellfire around you, scorching every nearby enemy.",
            48, 8, 12f, 10, ChatFormatting.RED,
            CastPattern.AROUND, CastEffects.of(ParticleKind.FLAME, 120, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    MAGMA_DOMAIN("Magma Domain", "Flood your aim point with molten earth that burns and staggers intruders.",
            62, 12, 13f, 18, ChatFormatting.GOLD,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.FLAME, 100, 5.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, true, false, SummonKind.NONE, 0)),
    PHOENIX_BURST("Phoenix Burst", "Erupt in a frontal blaze and rise renewed with stolen life.",
            55, 10, 11f, 14, ChatFormatting.RED,
            CastPattern.CONE, CastEffects.of(ParticleKind.FLAME, 100, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 8, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    CINDER_CHAIN("Cinder Chain", "Kindle a target and watch embers leap to every foe nearby.",
            50, 9, 13f, 24, ChatFormatting.GOLD,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.FLAME, 80, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ASH_WAVE("Ash Wave", "Sweep a choking wave of cinders across a wide frontal arc.",
            42, 7, 10f, 16, ChatFormatting.GRAY,
            CastPattern.CONE, CastEffects.of(ParticleKind.FLAME, 60, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 80}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    BLAZE_RING("Blaze Ring", "Orbit searing motes that slash everything within arm's reach.",
            38, 6, 9f, 9, ChatFormatting.GOLD,
            CastPattern.AROUND, CastEffects.of(ParticleKind.FLAME, 80, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ICE_LANCE("Ice Lance", "Impale a distant target on a spear of absolute zero.",
            34, 4, 15f, 28, ChatFormatting.AQUA,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{2, 100}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    GLACIAL_NOVA("Glacial Nova", "Shatter the air around you into razor ice that deep-freezes foes.",
            50, 8, 12f, 10, ChatFormatting.AQUA,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{3, 120}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    PERMAFROST_DOMAIN("Permafrost Domain", "Claim ground as frozen tundra that cripples all who enter.",
            64, 12, 12f, 18, ChatFormatting.AQUA,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 6, 5, 0.6f, 0.45f, new int[]{3, 140}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SHATTER_BOLT("Shatter Bolt", "Punch through armour with a bolt that explodes into ice shards.",
            46, 7, 18f, 26, ChatFormatting.AQUA,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{1, 80}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    BLIZZARD_VORTEX("Blizzard Vortex", "Summon a whirling blizzard at your aim point.",
            66, 11, 14f, 20, ChatFormatting.AQUA,
            CastPattern.AIM, CastEffects.of(ParticleKind.ARCANE, 0, 5.5, 5, 0.6f, 0.45f, new int[]{2, 120}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    FROST_CHAIN("Frost Chain", "Freeze a target and let rime crackle across nearby enemies.",
            52, 9, 12f, 24, ChatFormatting.AQUA,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{2, 100}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    CRYO_PULSE("Cryo Pulse", "Emit a radial frost pulse that numbs every nearby creature.",
            40, 7, 10f, 11, ChatFormatting.AQUA,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{2, 90}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    GALE_BEAM("Gale Beam", "Focus a cutting gust into a single devastating line.",
            28, 4, 11f, 26, ChatFormatting.WHITE,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, true, SummonKind.NONE, 0)),
    TORNADO_DOMAIN("Tornado Domain", "Anchor a cyclone at your aim point that hurls foes skyward.",
            58, 11, 10f, 18, ChatFormatting.WHITE,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, true, false, SummonKind.NONE, 0)),
    CYCLONE_NOVA("Cyclone Nova", "Unleash a 360° windburst that repels and shreds nearby enemies.",
            44, 8, 9f, 10, ChatFormatting.WHITE,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, true, false, SummonKind.NONE, 0)),
    ZEPHYR_CHAIN("Zephyr Chain", "Strike one foe and ride the wind to stagger a chain of targets.",
            48, 9, 10f, 22, ChatFormatting.WHITE,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, true, SummonKind.NONE, 0)),
    HURRICANE_CONE("Hurricane Cone", "Channel a hurricane cone that shreds and scatters the front ranks.",
            42, 7, 11f, 15, ChatFormatting.WHITE,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, true, SummonKind.NONE, 0)),
    MIST_VEIL("Mist Veil", "Shroud yourself in mist, blinding foes while you slip their grasp.",
            35, 6, 7f, 12, ChatFormatting.GRAY,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 80, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    THUNDER_BEAM("Thunder Beam", "Call a thunderbolt down your sightline into the first foe struck.",
            38, 5, 16f, 28, ChatFormatting.YELLOW,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, true, false, false, SummonKind.NONE, 0)),
    STORM_NOVA("Storm Nova", "Erupt with lightning in every direction around you.",
            54, 9, 13f, 11, ChatFormatting.YELLOW,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, true, false, false, SummonKind.NONE, 0)),
    VOLT_DOMAIN("Volt Domain", "Electrify an area with cascading arcs and static burns.",
            68, 12, 14f, 20, ChatFormatting.YELLOW,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 6, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, true, false, false, SummonKind.NONE, 0)),
    STATIC_CHAIN("Static Chain", "Zap a primary target and watch voltage leap to bystanders.",
            52, 9, 14f, 26, ChatFormatting.YELLOW,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 6, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, true, false, false, SummonKind.NONE, 0)),
    EMP_BLAST("EMP Blast", "Discharge a cone of electromagnetic force that weakens machines and flesh alike.",
            46, 8, 11f, 14, ChatFormatting.YELLOW,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{2, 120}, 0, 0, 0, 0, 0, true, false, false, SummonKind.NONE, 0)),
    BALL_LIGHTNING("Ball Lightning", "Hurl an unstable orb that detonates into chained lightning.",
            60, 10, 17f, 22, ChatFormatting.YELLOW,
            CastPattern.AIM, CastEffects.of(ParticleKind.ARCANE, 0, 4.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, true, false, false, SummonKind.NONE, 0)),
    VOID_BEAM("Void Beam", "Shear reality with a beam that withers everything it touches.",
            56, 9, 18f, 30, ChatFormatting.DARK_PURPLE,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 100}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ENTROPY_NOVA("Entropy Nova", "Unmake order in a burst around you, rotting and weakening foes.",
            62, 11, 13f, 10, ChatFormatting.DARK_PURPLE,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{2, 120}, new int[]{1, 120}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    RIFT_DOMAIN("Rift Domain", "Tear open a void rift at your aim point that devours intruders.",
            72, 13, 15f, 18, ChatFormatting.DARK_PURPLE,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 5.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 100}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ABYSS_CHAIN("Abyss Chain", "Mark a victim and let the abyss hunger spread to their allies.",
            58, 10, 14f, 26, ChatFormatting.DARK_PURPLE,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 80}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    PHASE_LANCE("Phase Lance", "Phase through defenses to impale a lone target for massive damage.",
            50, 8, 24f, 24, ChatFormatting.DARK_PURPLE,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SINGULARITY("Singularity", "Collapse space at your aim point, pulling and rending everything caught.",
            78, 14, 16f, 20, ChatFormatting.DARK_PURPLE,
            CastPattern.PULL, CastEffects.of(ParticleKind.ARCANE, 0, 5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 60}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ARCANE_BEAM("Arcane Beam", "Focus raw mana into a piercing violet beam.",
            36, 5, 16f, 28, ChatFormatting.LIGHT_PURPLE,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    PRISMATIC_NOVA("Prismatic Nova", "Detonate a rainbow burst of unstable arcana around you.",
            52, 9, 12f, 10, ChatFormatting.LIGHT_PURPLE,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    RUNE_DOMAIN("Rune Domain", "Inscribe a circle of runes that shreds trespassers with raw magic.",
            66, 12, 13f, 18, ChatFormatting.LIGHT_PURPLE,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 5.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    MANA_SURGE("Mana Surge", "Overcharge yourself and vent excess power in a frontal arc.",
            44, 8, 11f, 14, ChatFormatting.LIGHT_PURPLE,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 6, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ENCHANT_CHAIN("Enchant Chain", "Tag a foe with runes that ricochet arcane damage to nearby targets.",
            50, 9, 13f, 24, ChatFormatting.LIGHT_PURPLE,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5.5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ARCANE_ECHO("Arcane Echo", "Echo a second blast at your aim point after the initial pulse.",
            58, 10, 15f, 20, ChatFormatting.LIGHT_PURPLE,
            CastPattern.AIM, CastEffects.of(ParticleKind.ARCANE, 0, 4.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SHADOW_BEAM("Shadow Beam", "Lance shadow that withers and blinds your quarry.",
            48, 8, 14f, 28, ChatFormatting.DARK_GRAY,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 100}, new int[]{0, 0}, 60, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    NIGHT_NOVA("Night Nova", "Expand a sphere of absolute darkness that shreds nearby foes.",
            56, 10, 12f, 10, ChatFormatting.DARK_GRAY,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 80, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    UMBRA_DOMAIN("Umbra Domain", "Claim an area in living shadow that weakens and blinds intruders.",
            68, 12, 12f, 18, ChatFormatting.DARK_GRAY,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 6, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 100}, 100, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SOUL_CHAIN("Soul Chain", "Drain a target and let soul hunger leap between nearby enemies.",
            54, 9, 13f, 24, ChatFormatting.DARK_AQUA,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 2.5f, 0, false, false, false, SummonKind.NONE, 0)),
    PHANTOM_STRIKE("Phantom Strike", "Summon phantom blades that slash everything in a tight cone.",
            42, 7, 12f, 13, ChatFormatting.DARK_GRAY,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 60}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    GRIM_CONE("Grim Cone", "Exhale death in a cone, withering and slowing the living.",
            46, 8, 11f, 14, ChatFormatting.DARK_GRAY,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{1, 80}, new int[]{0, 0}, new int[]{1, 100}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    POISON_BEAM("Poison Beam", "Inject a concentrated venom bolt into a single target.",
            38, 5, 12f, 26, ChatFormatting.DARK_GREEN,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{2, 160}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    TOXIN_NOVA("Toxin Nova", "Vent toxic miasma in a ring around you.",
            50, 8, 10f, 10, ChatFormatting.DARK_GREEN,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{2, 140}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    PLAGUE_DOMAIN("Plague Domain", "Seed a plague zone that poisons and withers trespassers.",
            64, 12, 11f, 18, ChatFormatting.DARK_GREEN,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 5.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{2, 160}, new int[]{0, 80}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    VENOM_CHAIN("Venom Chain", "Envenom a target and spread the toxin to nearby foes.",
            48, 9, 11f, 22, ChatFormatting.DARK_GREEN,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{2, 120}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ACID_SPRAY("Acid Spray", "Spray corrosive acid across a wide frontal cone.",
            40, 7, 10f, 12, ChatFormatting.GREEN,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{1, 100}, new int[]{0, 0}, new int[]{1, 80}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    RADIANT_BEAM("Radiant Beam", "Smite a distant foe with a beam of consecrated light.",
            42, 6, 14f, 28, ChatFormatting.YELLOW,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 40, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    BLESSING_NOVA("Blessing Nova", "Erupt with holy light that mends allies and scorches undead nearby.",
            58, 10, 10f, 11, ChatFormatting.YELLOW,
            CastPattern.HOLY_NOVA, CastEffects.of(ParticleKind.HEART, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 8, 8, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SANCTUM_DOMAIN("Sanctum Domain", "Bless ground so allies within regenerate while foes are smitten.",
            66, 12, 10f, 16, ChatFormatting.YELLOW,
            CastPattern.SANCTUM, CastEffects.of(ParticleKind.HEART, 0, 6, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 6, 0, 0, false, false, false, SummonKind.NONE, 0)),
    DIVINE_CHAIN("Divine Chain", "Chain holy judgment between clustered enemies.",
            52, 9, 13f, 24, ChatFormatting.YELLOW,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5.5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    DIVINE_WRATH("Divine Wrath", "Unleash a cone of searing judgment from on high.",
            48, 8, 13f, 15, ChatFormatting.YELLOW,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 60, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    NECROTIC_BEAM("Necrotic Beam", "Rot a single target with concentrated necrotic force.",
            46, 7, 14f, 26, ChatFormatting.DARK_GREEN,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{2, 120}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ROT_NOVA("Rot Nova", "Pulse decay in every direction, withering the living.",
            56, 10, 12f, 10, ChatFormatting.DARK_GREEN,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{2, 140}, new int[]{1, 100}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    GRAVE_DOMAIN("Grave Domain", "Open graves at your aim point that weaken and rot intruders.",
            68, 12, 12f, 18, ChatFormatting.DARK_GRAY,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 5.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 120}, new int[]{2, 120}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    BONE_CHAIN("Bone Chain", "Skull shards leap from victim to victim along a necrotic chain.",
            52, 9, 12f, 22, ChatFormatting.GRAY,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 100}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SKULL_BURST("Skull Burst", "Detonate a cluster of screaming skulls at your aim point.",
            60, 10, 15f, 20, ChatFormatting.DARK_GRAY,
            CastPattern.AIM, CastEffects.of(ParticleKind.ARCANE, 0, 4.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{1, 80}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    BLOOD_BEAM("Blood Beam", "Lance a crimson beam that returns life to you from the wound.",
            44, 7, 14f, 26, ChatFormatting.RED,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 3, 0, false, false, false, SummonKind.NONE, 0)),
    CRIMSON_NOVA("Crimson Nova", "Explode in a blood nova, stealing vitality from nearby foes.",
            54, 9, 11f, 10, ChatFormatting.RED,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 2, 0, false, false, false, SummonKind.NONE, 0)),
    VAMPIRE_CHAIN("Vampire Chain", "Drain a target and siphon through a chain of victims.",
            56, 10, 12f, 22, ChatFormatting.RED,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 2.5f, 0, false, false, false, SummonKind.NONE, 0)),
    SANGUINE_RITE("Sanguine Rite", "Sacrifice your blood to empower a devastating frontal slash.",
            38, 6, 18f, 12, ChatFormatting.RED,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 4, false, false, false, SummonKind.NONE, 0)),
    NATURE_BEAM("Nature Beam", "Fire a thorn-laced beam that poisons and slows.",
            36, 5, 12f, 26, ChatFormatting.GREEN,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{1, 60}, new int[]{1, 100}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    VERDANT_NOVA("Verdant Nova", "Bloom life around you, healing allies while thorns punish foes.",
            56, 10, 9f, 11, ChatFormatting.GREEN,
            CastPattern.HOLY_NOVA, CastEffects.of(ParticleKind.HEART, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 10, 10, 0, 0, false, false, false, SummonKind.NONE, 0)),
    GROVE_DOMAIN("Grove Domain", "Root an area in living wood that entangles and poisons enemies.",
            62, 11, 10f, 18, ChatFormatting.GREEN,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 5.5, 5, 0.6f, 0.45f, new int[]{2, 100}, new int[]{1, 80}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    THORN_CHAIN("Thorn Chain", "Pierce a foe and let thorns whip to every nearby target.",
            48, 9, 11f, 22, ChatFormatting.GREEN,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{1, 80}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    WOLF_SUMMON("Spirit Pack", "Call spectral wolves to maul foes near your aim point.",
            70, 14, 8f, 18, ChatFormatting.GREEN,
            CastPattern.SUMMON, CastEffects.of(ParticleKind.SOUL, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.WOLF, 3)),
    CHAKRAM_VOLLEY("Chakram Volley", "Loose a fan of spinning chakrams down your forward arc.",
            32, 5, 10f, 18, ChatFormatting.WHITE,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    CHAKRAM_ORBIT("Chakram Orbit", "Orbit razor discs that cut everything nearby.",
            38, 6, 9f, 9, ChatFormatting.WHITE,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    RICOCHET_STORM("Ricochet Storm", "Unleash chakrams that ricochet wildly through nearby ranks.",
            44, 7, 11f, 12, ChatFormatting.WHITE,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    BOLT_SNIPER("Arc Bolt", "Fire a mana-charged sniper bolt through the first target aligned.",
            42, 6, 22f, 32, ChatFormatting.AQUA,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SHOTGUN_SPRAY("Scatter Shot", "Vent a short-range cone of arcane buckshot.",
            36, 5, 9f, 10, ChatFormatting.GRAY,
            CastPattern.CONE, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    PLASMA_LANCE("Plasma Lance", "Discharge a sustained plasma lance at extreme range.",
            52, 8, 20f, 30, ChatFormatting.LIGHT_PURPLE,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, true, false, false, SummonKind.NONE, 0)),
    STAR_BEAM("Star Beam", "Draw starfire into a beam that pierces the heavens.",
            50, 8, 17f, 30, ChatFormatting.LIGHT_PURPLE,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    COSMIC_NOVA("Cosmic Nova", "Expand a supernova burst around you.",
            64, 11, 14f, 11, ChatFormatting.LIGHT_PURPLE,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    METEOR_SHOWER("Meteor Shower", "Rain meteors across a wide zone at your aim point.",
            74, 13, 16f, 22, ChatFormatting.RED,
            CastPattern.AIM, CastEffects.of(ParticleKind.FLAME, 100, 6, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, true, false, SummonKind.NONE, 0)),
    ECLIPSE_DOMAIN("Eclipse Domain", "Cast an eclipse that blinds foes and empowers your strikes in the zone.",
            70, 12, 13f, 18, ChatFormatting.DARK_PURPLE,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 6, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 80, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    ASTRAL_CHAIN("Astral Chain", "Link enemies with astral threads that detonate in sequence.",
            58, 10, 14f, 26, ChatFormatting.LIGHT_PURPLE,
            CastPattern.CHAIN, CastEffects.of(ParticleKind.BEAM, 0, 0, 6, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    CHRONO_BEAM("Chrono Beam", "Strike a foe and lock them in temporal stasis.",
            48, 8, 14f, 26, ChatFormatting.AQUA,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{4, 80}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    TIME_WARP("Time Warp", "Warp time in a zone: haste allies, slow enemies.",
            62, 11, 8f, 16, ChatFormatting.AQUA,
            CastPattern.SANCTUM, CastEffects.of(ParticleKind.HEART, 0, 5.5, 5, 0.6f, 0.45f, new int[]{2, 100}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    STASIS_BOLT("Stasis Bolt", "Fire a bolt that nearly freezes a single target in place.",
            44, 7, 16f, 28, ChatFormatting.AQUA,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{5, 60}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    CRYSTAL_BEAM("Crystal Beam", "Focus gem-light into a piercing crystal lance.",
            40, 6, 15f, 28, ChatFormatting.AQUA,
            CastPattern.BEAM, CastEffects.of(ParticleKind.BEAM, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    GEM_NOVA("Gem Nova", "Shatter outward in a nova of razor crystal shards.",
            52, 9, 12f, 10, ChatFormatting.AQUA,
            CastPattern.AROUND, CastEffects.of(ParticleKind.ARCANE, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    SHARD_DOMAIN("Shard Domain", "Seed an area with erupting crystal spikes.",
            64, 11, 13f, 18, ChatFormatting.AQUA,
            CastPattern.DOMAIN, CastEffects.of(ParticleKind.ARCANE, 0, 5.5, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.NONE, 0)),
    GOLEM_SUMMON("Iron Aegis", "Summon a loyal iron golem at your aim point.",
            85, 16, 0f, 16, ChatFormatting.GRAY,
            CastPattern.SUMMON, CastEffects.of(ParticleKind.SOUL, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.GOLEM, 1)),
    VEX_SWARM("Vex Swarm", "Unleash a trio of vex shades on your target area.",
            72, 14, 6f, 18, ChatFormatting.LIGHT_PURPLE,
            CastPattern.SUMMON, CastEffects.of(ParticleKind.SOUL, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 0, 0, 0, 0, false, false, false, SummonKind.VEX, 3)),
    MEND_BEAM("Mend Beam", "Channel restorative light to yourself and allies ahead.",
            42, 7, 0f, 16, ChatFormatting.GREEN,
            CastPattern.HEAL, CastEffects.of(ParticleKind.HEART, 0, 0, 5, 0.6f, 0.45f, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, new int[]{0, 0}, 0, 10, 10, 0, 0, false, false, false, SummonKind.NONE, 0));

    public final String displayName;
    public final String description;
    public final int manaCost;
    public final int cooldownSeconds;
    public final float power;
    public final int range;
    public final ChatFormatting color;
    public final CastPattern pattern;
    public final CastEffects effects;

    RangedCast2(String displayName, String description, int manaCost, int cooldownSeconds,
                float power, int range, ChatFormatting color, CastPattern pattern, CastEffects effects) {
        this.displayName = displayName;
        this.description = description;
        this.manaCost = manaCost;
        this.cooldownSeconds = cooldownSeconds;
        this.power = power;
        this.range = range;
        this.color = color;
        this.pattern = pattern;
        this.effects = effects;
    }

    /** Targeted beams/chains require a foe in sight or Mana is refunded. */
    public boolean requiresTarget() {
        return pattern == CastPattern.BEAM || pattern == CastPattern.CHAIN;
    }
}
