package com.political.expansion2.accessories;

import com.political.items.Rarity;
import net.minecraft.ChatFormatting;
import net.minecraft.world.effect.MobEffects;

import java.util.List;

/** Generated by tools/gen-accessories2.js — do not edit by hand. */
final class Accessories2Catalog {

    private Accessories2Catalog() {}

    static void buildAccessories(List<AccessoryDef2> out) {
        Accessories2.acc(out, "acc2_ward_talisman", "Warding Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(8).defense(6));
        Accessories2.acc(out, "acc2_ward_ring", "Warding Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(20).defense(16).toughness(0.8));
        Accessories2.acc(out, "acc2_ward_charm", "Warding Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(32).defense(26).toughness(1.6));
        Accessories2.acc(out, "acc2_ward_band", "Warding Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(44).defense(36).toughness(2.4).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_ward_amulet", "Warding Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(56).defense(46).toughness(3.2).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_ward_badge", "Warding Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(68).defense(56).toughness(4).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_ward_rune", "Warding Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(80).defense(66).toughness(4.8).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_ward_totem", "Warding Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(92).defense(76).toughness(5.6).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_ward_artifact", "Warding Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(104).defense(86).toughness(6.4).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_ward_relic", "Warding Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "Turns aside blows with quiet resolve.",
                AccessoryDef2.bonus().health(116).defense(96).toughness(7.2).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_vigor_talisman", "Vigor Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(15).knockback(0.1));
        Accessories2.acc(out, "acc2_vigor_ring", "Vigor Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(33).knockback(0.1));
        Accessories2.acc(out, "acc2_vigor_charm", "Vigor Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(51).knockback(0.2));
        Accessories2.acc(out, "acc2_vigor_band", "Vigor Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(69).knockback(0.2));
        Accessories2.acc(out, "acc2_vigor_amulet", "Vigor Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(87).knockback(0.3).effect(MobEffects.REGENERATION, 0, "Regeneration I"));
        Accessories2.acc(out, "acc2_vigor_badge", "Vigor Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(105).knockback(0.4).effect(MobEffects.REGENERATION, 0, "Regeneration I"));
        Accessories2.acc(out, "acc2_vigor_rune", "Vigor Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(123).knockback(0.4).effect(MobEffects.REGENERATION, 0, "Regeneration I"));
        Accessories2.acc(out, "acc2_vigor_totem", "Vigor Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(141).knockback(0.5).effect(MobEffects.REGENERATION, 0, "Regeneration I"));
        Accessories2.acc(out, "acc2_vigor_artifact", "Vigor Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(159).knockback(0.5).effect(MobEffects.REGENERATION, 0, "Regeneration I"));
        Accessories2.acc(out, "acc2_vigor_relic", "Vigor Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "Life pulses through the metal like a second heartbeat.",
                AccessoryDef2.bonus().health(177).knockback(0.6).effect(MobEffects.REGENERATION, 0, "Regeneration I"));
        Accessories2.acc(out, "acc2_berserk_talisman", "Berserker Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(8).critDamage(10).ferocity(2));
        Accessories2.acc(out, "acc2_berserk_ring", "Berserker Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(16).critDamage(22).ferocity(4));
        Accessories2.acc(out, "acc2_berserk_charm", "Berserker Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(24).critDamage(34).ferocity(6).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_berserk_band", "Berserker Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(32).critDamage(46).ferocity(8).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_berserk_amulet", "Berserker Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(40).critDamage(58).ferocity(10).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_berserk_badge", "Berserker Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(48).critDamage(70).ferocity(12).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_berserk_rune", "Berserker Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(56).critDamage(82).ferocity(14).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_berserk_totem", "Berserker Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(64).critDamage(94).ferocity(16).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_berserk_artifact", "Berserker Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(72).critDamage(106).ferocity(18).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_berserk_relic", "Berserker Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "It hungers for the thrill of the fray.",
                AccessoryDef2.bonus().strength(80).critDamage(118).ferocity(20).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_swift_talisman", "Swift Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(8).attackSpeed(4).effect(MobEffects.SPEED, 0, "Speed I"));
        Accessories2.acc(out, "acc2_swift_ring", "Swift Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(16).attackSpeed(9).effect(MobEffects.SPEED, 1, "Speed I"));
        Accessories2.acc(out, "acc2_swift_charm", "Swift Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(24).attackSpeed(14).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_swift_band", "Swift Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(32).attackSpeed(19).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_swift_amulet", "Swift Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(40).attackSpeed(24).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_swift_badge", "Swift Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(48).attackSpeed(29).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_swift_rune", "Swift Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(56).attackSpeed(34).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_swift_totem", "Swift Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(64).attackSpeed(39).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_swift_artifact", "Swift Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(72).attackSpeed(44).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_swift_relic", "Swift Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "Your steps grow light and quick.",
                AccessoryDef2.bonus().speed(80).attackSpeed(49).effect(MobEffects.SPEED, 1, "Speed II"));
        Accessories2.acc(out, "acc2_scholar_talisman", "Scholar Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().manaRegen(1));
        Accessories2.acc(out, "acc2_scholar_ring", "Scholar Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(0.5).manaRegen(2.5));
        Accessories2.acc(out, "acc2_scholar_charm", "Scholar Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(1).manaRegen(4));
        Accessories2.acc(out, "acc2_scholar_band", "Scholar Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(1.5).manaRegen(5.5).effect(MobEffects.NIGHT_VISION, 0, "Night Vision"));
        Accessories2.acc(out, "acc2_scholar_amulet", "Scholar Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(2).manaRegen(7).effect(MobEffects.NIGHT_VISION, 0, "Night Vision"));
        Accessories2.acc(out, "acc2_scholar_badge", "Scholar Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(2.5).manaRegen(8.5).effect(MobEffects.NIGHT_VISION, 0, "Night Vision"));
        Accessories2.acc(out, "acc2_scholar_rune", "Scholar Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(3).manaRegen(10).effect(MobEffects.NIGHT_VISION, 0, "Night Vision"));
        Accessories2.acc(out, "acc2_scholar_totem", "Scholar Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(3.5).manaRegen(11.5).effect(MobEffects.NIGHT_VISION, 0, "Night Vision"));
        Accessories2.acc(out, "acc2_scholar_artifact", "Scholar Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(4).manaRegen(13).effect(MobEffects.NIGHT_VISION, 0, "Night Vision"));
        Accessories2.acc(out, "acc2_scholar_relic", "Scholar Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "Arcane study replenishes the mind.",
                AccessoryDef2.bonus().luck(4.5).manaRegen(14.5).effect(MobEffects.NIGHT_VISION, 0, "Night Vision"));
        Accessories2.acc(out, "acc2_cursed_talisman", "Cursed Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().cursedRegen(1));
        Accessories2.acc(out, "acc2_cursed_ring", "Cursed Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(4).cursedRegen(1.8));
        Accessories2.acc(out, "acc2_cursed_charm", "Cursed Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(8).cursedRegen(2.6));
        Accessories2.acc(out, "acc2_cursed_band", "Cursed Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(12).cursedRegen(3.4));
        Accessories2.acc(out, "acc2_cursed_amulet", "Cursed Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(16).cursedRegen(4.2).effect(MobEffects.DARKNESS, 0, "Darkness (harmless aura)"));
        Accessories2.acc(out, "acc2_cursed_badge", "Cursed Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(20).cursedRegen(5).effect(MobEffects.DARKNESS, 0, "Darkness (harmless aura)"));
        Accessories2.acc(out, "acc2_cursed_rune", "Cursed Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(24).cursedRegen(5.8).effect(MobEffects.DARKNESS, 0, "Darkness (harmless aura)"));
        Accessories2.acc(out, "acc2_cursed_totem", "Cursed Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(28).cursedRegen(6.6).effect(MobEffects.DARKNESS, 0, "Darkness (harmless aura)"));
        Accessories2.acc(out, "acc2_cursed_artifact", "Cursed Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(32).cursedRegen(7.4).effect(MobEffects.DARKNESS, 0, "Darkness (harmless aura)"));
        Accessories2.acc(out, "acc2_cursed_relic", "Cursed Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "A sealed sliver of cursed energy seeps back into you.",
                AccessoryDef2.bonus().strength(36).cursedRegen(8.2).effect(MobEffects.DARKNESS, 0, "Darkness (harmless aura)"));
        Accessories2.acc(out, "acc2_assassin_talisman", "Shadow Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().critChance(4).critDamage(12));
        Accessories2.acc(out, "acc2_assassin_ring", "Shadow Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(4).critChance(8).critDamage(26));
        Accessories2.acc(out, "acc2_assassin_charm", "Shadow Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(8).critChance(12).critDamage(40));
        Accessories2.acc(out, "acc2_assassin_band", "Shadow Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(12).critChance(16).critDamage(54).effect(MobEffects.INVISIBILITY, 0, "Invisibility (faint)"));
        Accessories2.acc(out, "acc2_assassin_amulet", "Shadow Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(16).critChance(20).critDamage(68).effect(MobEffects.INVISIBILITY, 0, "Invisibility (faint)"));
        Accessories2.acc(out, "acc2_assassin_badge", "Shadow Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(20).critChance(24).critDamage(82).effect(MobEffects.INVISIBILITY, 0, "Invisibility (faint)"));
        Accessories2.acc(out, "acc2_assassin_rune", "Shadow Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(24).critChance(28).critDamage(96).effect(MobEffects.INVISIBILITY, 0, "Invisibility (faint)"));
        Accessories2.acc(out, "acc2_assassin_totem", "Shadow Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(28).critChance(32).critDamage(110).effect(MobEffects.INVISIBILITY, 0, "Invisibility (faint)"));
        Accessories2.acc(out, "acc2_assassin_artifact", "Shadow Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(32).critChance(36).critDamage(124).effect(MobEffects.INVISIBILITY, 0, "Invisibility (faint)"));
        Accessories2.acc(out, "acc2_assassin_relic", "Shadow Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "Strike from the shadows, swift and sure.",
                AccessoryDef2.bonus().speed(36).critChance(40).critDamage(138).effect(MobEffects.INVISIBILITY, 0, "Invisibility (faint)"));
        Accessories2.acc(out, "acc2_phoenix_talisman", "Phoenix Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(10).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_ring", "Phoenix Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(20).defense(6).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_charm", "Phoenix Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(30).defense(12).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_band", "Phoenix Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(40).defense(18).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_amulet", "Phoenix Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(50).defense(24).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_badge", "Phoenix Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(60).defense(30).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_rune", "Phoenix Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(70).defense(36).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_totem", "Phoenix Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(80).defense(42).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_artifact", "Phoenix Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(90).defense(48).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_phoenix_relic", "Phoenix Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "Wreathed in embers that never burn its bearer.",
                AccessoryDef2.bonus().health(100).defense(54).effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
        Accessories2.acc(out, "acc2_frost_talisman", "Frost Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(5));
        Accessories2.acc(out, "acc2_frost_ring", "Frost Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(13).speed(5));
        Accessories2.acc(out, "acc2_frost_charm", "Frost Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(21).speed(10).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_frost_band", "Frost Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(29).speed(15).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_frost_amulet", "Frost Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(37).speed(20).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_frost_badge", "Frost Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(45).speed(25).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_frost_rune", "Frost Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(53).speed(30).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_frost_totem", "Frost Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(61).speed(35).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_frost_artifact", "Frost Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(69).speed(40).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_frost_relic", "Frost Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "Cold clarity sharpens every movement.",
                AccessoryDef2.bonus().defense(77).speed(45).effect(MobEffects.SLOW_FALLING, 0, "Slow Falling"));
        Accessories2.acc(out, "acc2_void_talisman", "Void Talisman", AccessoryDef2.Type.TALISMAN, Rarity.COMMON,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus());
        Accessories2.acc(out, "acc2_void_ring", "Void Ring", AccessoryDef2.Type.RING, Rarity.COMMON,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(15).defense(10).strength(8).critChance(3).manaRegen(1.2).cursedRegen(0.8));
        Accessories2.acc(out, "acc2_void_charm", "Void Charm", AccessoryDef2.Type.CHARM, Rarity.UNCOMMON,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(30).defense(20).strength(16).critChance(6).manaRegen(2.4).cursedRegen(1.6));
        Accessories2.acc(out, "acc2_void_band", "Void Band", AccessoryDef2.Type.BAND, Rarity.RARE,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(45).defense(30).strength(24).critChance(9).manaRegen(3.6).cursedRegen(2.4));
        Accessories2.acc(out, "acc2_void_amulet", "Void Amulet", AccessoryDef2.Type.AMULET, Rarity.EPIC,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(60).defense(40).strength(32).critChance(12).manaRegen(4.8).cursedRegen(3.2).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_void_badge", "Void Badge", AccessoryDef2.Type.BADGE, Rarity.EPIC,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(75).defense(50).strength(40).critChance(15).manaRegen(6).cursedRegen(4).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_void_rune", "Void Rune", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(90).defense(60).strength(48).critChance(18).manaRegen(7.2).cursedRegen(4.8).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_void_totem", "Void Totem", AccessoryDef2.Type.TOTEM, Rarity.MYTHIC,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(105).defense(70).strength(56).critChance(21).manaRegen(8.4).cursedRegen(5.6).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_void_artifact", "Void Artifact", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(120).defense(80).strength(64).critChance(24).manaRegen(9.6).cursedRegen(6.4).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_void_relic", "Void Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "The abyss whispers power into your bones.",
                AccessoryDef2.bonus().health(135).defense(90).strength(72).critChance(27).manaRegen(10.8).cursedRegen(7.2).effect(MobEffects.STRENGTH, 0, "Strength I"));
        Accessories2.acc(out, "acc2_paragon_crest", "Paragon Crest", AccessoryDef2.Type.BADGE, Rarity.MYTHIC,
                "The mark of one who has surpassed every trial.",
                AccessoryDef2.bonus().health(100).defense(50).strength(30).critChance(10).manaRegen(6).effect(MobEffects.RESISTANCE, 0, "Resistance I"));
        Accessories2.acc(out, "acc2_eternal_sigil", "Eternal Sigil", AccessoryDef2.Type.RUNE, Rarity.MYTHIC,
                "A rune carved before the first age of kings.",
                AccessoryDef2.bonus().health(80).defense(40).manaRegen(8).cursedRegen(5).effect(MobEffects.REGENERATION, 1, "Regeneration II"));
        Accessories2.acc(out, "acc2_sovereign_relic", "Sovereign Relic", AccessoryDef2.Type.RELIC, Rarity.MYTHIC,
                "The crown-jewel of a fallen empire.",
                AccessoryDef2.bonus().health(140).defense(70).strength(50).critDamage(80).ferocity(15).effect(MobEffects.STRENGTH, 1, "Strength II"));
        Accessories2.acc(out, "acc2_ascendant_orb", "Ascendant Orb", AccessoryDef2.Type.ARTIFACT, Rarity.MYTHIC,
                "A miniature star bound in gold filigree.",
                AccessoryDef2.bonus().speed(30).attackSpeed(25).luck(4).manaRegen(12).effect(MobEffects.JUMP_BOOST, 2, "Jump Boost III"));
        Accessories2.acc(out, "acc2_abaddon_talisman", "Abaddon Talisman", AccessoryDef2.Type.TALISMAN, Rarity.MYTHIC,
                "Named for the end of all things.",
                AccessoryDef2.bonus().strength(70).critChance(25).critDamage(120).ferocity(22).cursedRegen(4).effect(MobEffects.STRENGTH, 1, "Strength II").effect(MobEffects.FIRE_RESISTANCE, 0, "Fire Resistance"));
    }

    static void buildConsumables(List<ConsumableDef2> out) {
        Accessories2.con(out, "acc2_healing_draught", "Healing Draught", ConsumableDef2.Type.POTION, Rarity.COMMON,
                "Restores 25% of max Health.", "Warmth knits your wounds.", ChatFormatting.RED, 16,
                sp -> Accessories2.healFrac(sp, 0.25));
        Accessories2.con(out, "acc2_healing_potion", "Healing Potion", ConsumableDef2.Type.POTION, Rarity.UNCOMMON,
                "Restores 50% of max Health.", "Your wounds close swiftly.", ChatFormatting.RED, 16,
                sp -> Accessories2.healFrac(sp, 0.5));
        Accessories2.con(out, "acc2_greater_healing_potion", "Greater Healing Potion", ConsumableDef2.Type.POTION, Rarity.RARE,
                "Restores 100% of max Health.", "You are made whole again.", ChatFormatting.RED, 16,
                sp -> Accessories2.healFrac(sp, 1));
        Accessories2.con(out, "acc2_mana_draught", "Mana Draught", ConsumableDef2.Type.POTION, Rarity.COMMON,
                "Restores 25% of max Mana.", "Mana trickles back.", ChatFormatting.AQUA, 16,
                sp -> Accessories2.restoreMana(sp, 0.25));
        Accessories2.con(out, "acc2_mana_potion", "Mana Potion", ConsumableDef2.Type.POTION, Rarity.UNCOMMON,
                "Restores 50% of max Mana.", "Your mind fills with mana.", ChatFormatting.AQUA, 16,
                sp -> Accessories2.restoreMana(sp, 0.5));
        Accessories2.con(out, "acc2_greater_mana_potion", "Greater Mana Potion", ConsumableDef2.Type.POTION, Rarity.RARE,
                "Restores 100% of max Mana.", "Mana floods your veins.", ChatFormatting.AQUA, 16,
                sp -> Accessories2.restoreMana(sp, 1));
        Accessories2.con(out, "acc2_cursed_vial", "Cursed Energy Vial", ConsumableDef2.Type.POTION, Rarity.RARE,
                "Restores 40% of max Cursed Energy.", "Cursed energy boils within.", ChatFormatting.DARK_PURPLE, 16,
                sp -> Accessories2.restoreCursed(sp, 0.4));
        Accessories2.con(out, "acc2_greater_cursed_vial", "Greater Cursed Vial", ConsumableDef2.Type.POTION, Rarity.EPIC,
                "Restores 80% of max Cursed Energy.", "Your curse surges to the brim.", ChatFormatting.DARK_PURPLE, 16,
                sp -> Accessories2.restoreCursed(sp, 0.8));
        Accessories2.con(out, "acc2_vitality_tonic", "Vitality Tonic", ConsumableDef2.Type.POTION, Rarity.UNCOMMON,
                "Restores 35% of max Health.", "Vitality returns.", ChatFormatting.RED, 16,
                sp -> { Accessories2.healFrac(sp, 0.35); Accessories2.buff(sp, MobEffects.REGENERATION, 30, 0); return true; });
        Accessories2.con(out, "acc2_arcane_tonic", "Arcane Tonic", ConsumableDef2.Type.POTION, Rarity.UNCOMMON,
                "Restores 35% of max Mana.", "Arcane currents stir.", ChatFormatting.AQUA, 16,
                sp -> { Accessories2.restoreMana(sp, 0.35); Accessories2.buff(sp, MobEffects.NIGHT_VISION, 120, 0); return true; });
        Accessories2.con(out, "acc2_spirit_tonic", "Spirit Tonic", ConsumableDef2.Type.POTION, Rarity.RARE,
                "Restores 30% of max Cursed Energy.", "Spirits lend their strength.", ChatFormatting.DARK_PURPLE, 16,
                sp -> { if (!Accessories2.restoreCursed(sp, 0.3)) return false; Accessories2.buff(sp, MobEffects.REGENERATION, 20, 0); return true; });
        Accessories2.con(out, "acc2_restoration_flask", "Restoration Flask", ConsumableDef2.Type.POTION, Rarity.EPIC,
                "Restores Health, Mana, and Cursed Energy.", "Body, mind, and curse align.", ChatFormatting.LIGHT_PURPLE, 16,
                Accessories2::tripleRestore);
        Accessories2.con(out, "acc2_elixir_strength", "Elixir of Strength", ConsumableDef2.Type.ELIXIR, Rarity.RARE,
                "STRENGTH 90s", "Power surges into your limbs.", ChatFormatting.RED, 16,
                sp -> { Accessories2.buff(sp, MobEffects.STRENGTH, 90, 2); return true; });
        Accessories2.con(out, "acc2_elixir_swiftness", "Elixir of Swiftness", ConsumableDef2.Type.ELIXIR, Rarity.UNCOMMON,
                "SPEED 120s", "The world slows around you.", ChatFormatting.WHITE, 16,
                sp -> { Accessories2.buff(sp, MobEffects.SPEED, 120, 2); return true; });
        Accessories2.con(out, "acc2_elixir_iron_skin", "Elixir of Iron Skin", ConsumableDef2.Type.ELIXIR, Rarity.RARE,
                "RESISTANCE 60s", "Your skin hardens like iron.", ChatFormatting.GREEN, 16,
                sp -> { Accessories2.buff(sp, MobEffects.RESISTANCE, 60, 1); return true; });
        Accessories2.con(out, "acc2_elixir_haste", "Elixir of Haste", ConsumableDef2.Type.ELIXIR, Rarity.UNCOMMON,
                "HASTE 120s", "Your hands move in a blur.", ChatFormatting.GOLD, 16,
                sp -> { Accessories2.buff(sp, MobEffects.HASTE, 120, 2); return true; });
        Accessories2.con(out, "acc2_elixir_phoenix", "Elixir of the Phoenix", ConsumableDef2.Type.ELIXIR, Rarity.EPIC,
                "FIRE_RESISTANCE 60s + REGENERATION 60s", "Phoenix fire wreathes you.", ChatFormatting.GOLD, 16,
                sp -> { Accessories2.buff(sp, MobEffects.FIRE_RESISTANCE, 60, 0); Accessories2.buff(sp, MobEffects.REGENERATION, 60, 1); return true; });
        Accessories2.con(out, "acc2_elixir_berserk", "Berserk Brew", ConsumableDef2.Type.ELIXIR, Rarity.EPIC,
                "STRENGTH 90s + SPEED 90s", "A red haze descends.", ChatFormatting.DARK_RED, 16,
                sp -> { Accessories2.buff(sp, MobEffects.STRENGTH, 90, 3); Accessories2.buff(sp, MobEffects.SPEED, 90, 1); return true; });
        Accessories2.con(out, "acc2_elixir_invisibility", "Invisibility Draught", ConsumableDef2.Type.ELIXIR, Rarity.RARE,
                "INVISIBILITY 45s", "You fade from sight.", ChatFormatting.GRAY, 16,
                sp -> { Accessories2.buff(sp, MobEffects.INVISIBILITY, 45, 0); return true; });
        Accessories2.con(out, "acc2_elixir_night_owl", "Night Owl Tonic", ConsumableDef2.Type.ELIXIR, Rarity.COMMON,
                "NIGHT_VISION 300s", "Your eyes drink in the dark.", ChatFormatting.BLUE, 16,
                sp -> { Accessories2.buff(sp, MobEffects.NIGHT_VISION, 300, 0); return true; });
        Accessories2.con(out, "acc2_elixir_gills", "Gills Brew", ConsumableDef2.Type.ELIXIR, Rarity.UNCOMMON,
                "WATER_BREATHING 180s + DOLPHINS_GRACE 180s", "You breathe the deep.", ChatFormatting.AQUA, 16,
                sp -> { Accessories2.buff(sp, MobEffects.WATER_BREATHING, 180, 0); Accessories2.buff(sp, MobEffects.DOLPHINS_GRACE, 180, 0); return true; });
        Accessories2.con(out, "acc2_elixir_titan", "Titan Tonic", ConsumableDef2.Type.ELIXIR, Rarity.EPIC,
                "HEALTH_BOOST 120s + ABSORPTION 120s", "You swell with titanic vitality.", ChatFormatting.RED, 16,
                sp -> { Accessories2.buff(sp, MobEffects.HEALTH_BOOST, 120, 1); Accessories2.buff(sp, MobEffects.ABSORPTION, 120, 1); return true; });
        Accessories2.con(out, "acc2_elixir_frost", "Frost Elixir", ConsumableDef2.Type.ELIXIR, Rarity.RARE,
                "SLOW_FALLING 90s + RESISTANCE 60s", "Ice crystallizes on your skin.", ChatFormatting.AQUA, 16,
                sp -> { Accessories2.buff(sp, MobEffects.SLOW_FALLING, 90, 0); Accessories2.buff(sp, MobEffects.RESISTANCE, 60, 0); return true; });
        Accessories2.con(out, "acc2_elixir_poison", "Antidote Elixir", ConsumableDef2.Type.ELIXIR, Rarity.UNCOMMON,
                "Cures poison and grants brief immunity.", "Toxins burn away.", ChatFormatting.GREEN, 16,
                Accessories2::clearPoison);
        Accessories2.con(out, "acc2_elixir_rage", "Rage Elixir", ConsumableDef2.Type.ELIXIR, Rarity.LEGENDARY,
                "STRENGTH 60s + SPEED 60s", "Unbridled fury takes hold.", ChatFormatting.DARK_RED, 16,
                sp -> { Accessories2.buff(sp, MobEffects.STRENGTH, 60, 4); Accessories2.buff(sp, MobEffects.SPEED, 60, 2); return true; });
        Accessories2.con(out, "acc2_elixir_clarity", "Clarity Elixir", ConsumableDef2.Type.ELIXIR, Rarity.RARE,
                "HASTE 90s + NIGHT_VISION 90s", "Your senses sharpen.", ChatFormatting.YELLOW, 16,
                sp -> { Accessories2.buff(sp, MobEffects.HASTE, 90, 1); Accessories2.buff(sp, MobEffects.NIGHT_VISION, 90, 0); return true; });
        Accessories2.con(out, "acc2_elixir_void", "Void Elixir", ConsumableDef2.Type.ELIXIR, Rarity.LEGENDARY,
                "STRENGTH 45s + INVISIBILITY 45s", "The void embraces you.", ChatFormatting.DARK_PURPLE, 16,
                sp -> { Accessories2.buff(sp, MobEffects.STRENGTH, 45, 2); Accessories2.buff(sp, MobEffects.INVISIBILITY, 45, 0); return true; });
        Accessories2.con(out, "acc2_scroll_recall", "Scroll of Recall", ConsumableDef2.Type.SCROLL, Rarity.RARE,
                "Teleports you to world spawn.", "The runes pull you home.", ChatFormatting.LIGHT_PURPLE, 16,
                Accessories2::recallToSpawn);
        Accessories2.con(out, "acc2_scroll_blink", "Scroll of Blink", ConsumableDef2.Type.SCROLL, Rarity.UNCOMMON,
                "Blink 8 blocks forward.", "Space folds around you.", ChatFormatting.LIGHT_PURPLE, 16,
                sp -> Accessories2.blinkForward(sp, 8));
        Accessories2.con(out, "acc2_scroll_blink_far", "Scroll of Far Blink", ConsumableDef2.Type.SCROLL, Rarity.RARE,
                "Blink 16 blocks forward.", "You leap through folded space.", ChatFormatting.LIGHT_PURPLE, 16,
                sp -> Accessories2.blinkForward(sp, 16));
        Accessories2.con(out, "acc2_scroll_ascension", "Scroll of Ascension", ConsumableDef2.Type.SCROLL, Rarity.RARE,
                "Teleports you to the surface.", "You rise toward the sky.", ChatFormatting.LIGHT_PURPLE, 16,
                Accessories2::ascendToSurface);
        Accessories2.con(out, "acc2_scroll_warding", "Scroll of Warding", ConsumableDef2.Type.SCROLL, Rarity.EPIC,
                "Resistance II + Absorption II.", "A protective ward flares.", ChatFormatting.GREEN, 16,
                sp -> { Accessories2.buff(sp, MobEffects.RESISTANCE, 60, 1); Accessories2.buff(sp, MobEffects.ABSORPTION, 60, 1); return true; });
        Accessories2.con(out, "acc2_scroll_haste", "Scroll of Haste", ConsumableDef2.Type.SCROLL, Rarity.UNCOMMON,
                "Speed II + Haste II.", "Quickening runes race across your skin.", ChatFormatting.YELLOW, 16,
                sp -> { Accessories2.buff(sp, MobEffects.SPEED, 60, 1); Accessories2.buff(sp, MobEffects.HASTE, 60, 1); return true; });
        Accessories2.con(out, "acc2_scroll_fury", "Scroll of Fury", ConsumableDef2.Type.SCROLL, Rarity.EPIC,
                "Strength III + Speed II.", "Battle runes ignite.", ChatFormatting.RED, 16,
                sp -> { Accessories2.buff(sp, MobEffects.STRENGTH, 45, 2); Accessories2.buff(sp, MobEffects.SPEED, 45, 1); return true; });
        Accessories2.con(out, "acc2_scroll_sanctuary", "Scroll of Sanctuary", ConsumableDef2.Type.SCROLL, Rarity.LEGENDARY,
                "Regeneration III + Resistance III.", "Holy light shelters you.", ChatFormatting.GOLD, 16,
                sp -> { Accessories2.buff(sp, MobEffects.REGENERATION, 30, 2); Accessories2.buff(sp, MobEffects.RESISTANCE, 30, 2); return true; });
        Accessories2.con(out, "acc2_scroll_mana", "Scroll of Arcane Flow", ConsumableDef2.Type.SCROLL, Rarity.RARE,
                "Restores 60% Mana.", "Arcane currents surge.", ChatFormatting.AQUA, 16,
                sp -> Accessories2.restoreMana(sp, 0.6));
        Accessories2.con(out, "acc2_scroll_heal", "Scroll of Mending", ConsumableDef2.Type.SCROLL, Rarity.RARE,
                "Heals 50% max Health.", "Mending runes knit your flesh.", ChatFormatting.RED, 16,
                sp -> Accessories2.healFrac(sp, 0.5));
        Accessories2.con(out, "acc2_scroll_curse", "Scroll of Cursed Binding", ConsumableDef2.Type.SCROLL, Rarity.EPIC,
                "Restores 50% Cursed Energy.", "Dark runes bind power to you.", ChatFormatting.DARK_PURPLE, 16,
                sp -> Accessories2.restoreCursed(sp, 0.5));
        Accessories2.con(out, "acc2_scroll_levitation", "Scroll of Levitation", ConsumableDef2.Type.SCROLL, Rarity.EPIC,
                "Brief levitation then slow fall.", "You are lifted by ancient glyphs.", ChatFormatting.WHITE, 16,
                sp -> { Accessories2.buff(sp, MobEffects.LEVITATION, 8, 0); Accessories2.buff(sp, MobEffects.SLOW_FALLING, 30, 0); return true; });
        Accessories2.con(out, "acc2_food_hearty_stew", "Hearty Stew", ConsumableDef2.Type.FOOD, Rarity.COMMON,
                "Sates hunger and heals a little.", "The hot stew restores you.", ChatFormatting.GOLD, 16,
                sp -> Accessories2.foodHeal(sp, 0.12, 2));
        Accessories2.con(out, "acc2_food_golden_feast", "Golden Feast", ConsumableDef2.Type.FOOD, Rarity.RARE,
                "Saturation, Regeneration, and Absorption.", "You feast like royalty.", ChatFormatting.GOLD, 16,
                Accessories2::foodGolden);
        Accessories2.con(out, "acc2_food_spirit_bread", "Spirit Bread", ConsumableDef2.Type.FOOD, Rarity.UNCOMMON,
                "Sates hunger and restores Mana.", "Blessed bread feeds body and mind.", ChatFormatting.AQUA, 16,
                sp -> Accessories2.foodMana(sp, 0.25, 2));
        Accessories2.con(out, "acc2_food_cursed_jerky", "Cursed Jerky", ConsumableDef2.Type.FOOD, Rarity.RARE,
                "Sates hunger and restores Cursed Energy.", "Bitter, but it stokes your curse.", ChatFormatting.DARK_PURPLE, 16,
                sp -> Accessories2.foodCursed(sp, 0.25, 2));
        Accessories2.con(out, "acc2_food_mushroom_risotto", "Mushroom Risotto", ConsumableDef2.Type.FOOD, Rarity.UNCOMMON,
                "Restorative food consumed on use.", "Earthy warmth spreads through you.", ChatFormatting.GREEN, 16,
                sp -> { Accessories2.foodHeal(sp, 0.08, 3); Accessories2.buff(sp, MobEffects.REGENERATION, 15, 0); return true; });
        Accessories2.con(out, "acc2_food_sea_salt_fish", "Sea-Salt Fish", ConsumableDef2.Type.FOOD, Rarity.COMMON,
                "Restorative food consumed on use.", "The sea's blessing lingers.", ChatFormatting.AQUA, 16,
                sp -> { Accessories2.foodHeal(sp, 0.1, 2); Accessories2.buff(sp, MobEffects.WATER_BREATHING, 60, 0); return true; });
        Accessories2.con(out, "acc2_food_honey_cake", "Honey Cake", ConsumableDef2.Type.FOOD, Rarity.UNCOMMON,
                "Restorative food consumed on use.", "Sweet energy courses through you.", ChatFormatting.YELLOW, 16,
                sp -> { Accessories2.foodHeal(sp, 0.08, 3); Accessories2.buff(sp, MobEffects.SPEED, 30, 0); return true; });
        Accessories2.con(out, "acc2_food_war_ration", "War Ration", ConsumableDef2.Type.FOOD, Rarity.RARE,
                "Restorative food consumed on use.", "Soldier's fuel for the front line.", ChatFormatting.RED, 16,
                sp -> { Accessories2.foodHeal(sp, 0.15, 3); Accessories2.buff(sp, MobEffects.STRENGTH, 30, 0); return true; });
        Accessories2.con(out, "acc2_food_starfruit_tart", "Starfruit Tart", ConsumableDef2.Type.FOOD, Rarity.EPIC,
                "Fully restores Health, Mana, and Cursed Energy.", "Cosmic sweetness restores all.", ChatFormatting.LIGHT_PURPLE, 16,
                Accessories2::foodTriple);
        Accessories2.con(out, "acc2_food_void_soup", "Void Soup", ConsumableDef2.Type.FOOD, Rarity.LEGENDARY,
                "Massive heal plus Strength and Resistance.", "The abyss feeds you and takes nothing.", ChatFormatting.DARK_PURPLE, 16,
                Accessories2::foodVoid);
        Accessories2.con(out, "acc2_bomb_flash", "Flash Bomb", ConsumableDef2.Type.BOMB, Rarity.UNCOMMON,
                "Detonates on use. Radius 6 blocks.", "A blinding flash erupts!", ChatFormatting.YELLOW, 8,
                sp -> Accessories2.bombFlash(sp, 6));
        Accessories2.con(out, "acc2_bomb_fire", "Fire Bomb", ConsumableDef2.Type.BOMB, Rarity.RARE,
                "Detonates on use. Radius 4 blocks.", "Flames burst outward!", ChatFormatting.RED, 8,
                sp -> Accessories2.bombFire(sp, 4));
        Accessories2.con(out, "acc2_bomb_frost", "Frost Bomb", ConsumableDef2.Type.BOMB, Rarity.RARE,
                "Detonates on use. Radius 5 blocks.", "Ice shards explode!", ChatFormatting.AQUA, 8,
                sp -> Accessories2.bombFrost(sp, 5));
        Accessories2.con(out, "acc2_bomb_poison", "Poison Bomb", ConsumableDef2.Type.BOMB, Rarity.RARE,
                "Detonates on use. Radius 5 blocks.", "Toxic vapors spread!", ChatFormatting.GREEN, 8,
                sp -> Accessories2.bombPoison(sp, 5));
        Accessories2.con(out, "acc2_bomb_smoke", "Smoke Bomb", ConsumableDef2.Type.BOMB, Rarity.COMMON,
                "Detonates on use. Radius 4 blocks.", "Thick smoke billows out!", ChatFormatting.GRAY, 8,
                sp -> Accessories2.bombSmoke(sp, 4));
        Accessories2.con(out, "acc2_bomb_holy", "Holy Bomb", ConsumableDef2.Type.BOMB, Rarity.EPIC,
                "Detonates on use. Radius 5 blocks.", "Radiant force blasts undead!", ChatFormatting.GOLD, 8,
                sp -> Accessories2.bombHoly(sp, 5));
        Accessories2.con(out, "acc2_bomb_void", "Void Bomb", ConsumableDef2.Type.BOMB, Rarity.LEGENDARY,
                "Detonates on use. Radius 6 blocks.", "Reality tears at the seams!", ChatFormatting.DARK_PURPLE, 8,
                sp -> Accessories2.bombVoid(sp, 6));
        Accessories2.con(out, "acc2_bomb_gravity", "Gravity Bomb", ConsumableDef2.Type.BOMB, Rarity.EPIC,
                "Detonates on use. Radius 5 blocks.", "Enemies are pulled inward!", ChatFormatting.LIGHT_PURPLE, 8,
                sp -> Accessories2.bombGravity(sp, 5));
        Accessories2.con(out, "acc2_bomb_shock", "Shock Bomb", ConsumableDef2.Type.BOMB, Rarity.UNCOMMON,
                "Detonates on use. Radius 4 blocks.", "Lightning crackles outward!", ChatFormatting.YELLOW, 8,
                sp -> Accessories2.bombShock(sp, 4));
        Accessories2.con(out, "acc2_bomb_healing", "Healing Bomb", ConsumableDef2.Type.BOMB, Rarity.RARE,
                "Detonates on use. Radius 5 blocks.", "Restorative mist washes over allies!", ChatFormatting.RED, 8,
                sp -> Accessories2.bombHeal(sp, 5));
        Accessories2.con(out, "acc2_bomb_cursed", "Cursed Bomb", ConsumableDef2.Type.BOMB, Rarity.EPIC,
                "Detonates on use. Radius 5 blocks.", "Cursed energy detonates!", ChatFormatting.DARK_PURPLE, 8,
                sp -> Accessories2.bombCursed(sp, 5));
    }
}
