package com.political.expansion2.quests;

public enum QuestKind {
    FETCH, KILL_SPIRIT, KILL_MOB, DELIVER, ELECTION, BANK_DEPOSIT,
    AWAKEN_CE, BOSS, BOUNTY, COLLECT_COINS, EXORCISE_COUNT, DEPOSIT_TREASURY, HOLD_ITEM, REACH_GRADE
}
