/**
 * Single source of truth for Phase-2 global cuisine foods (food2_*).
 * Used by gen-food2.js (textures + lang) and build-food2-java.js (Food2Items.java).
 */

function W(fn, opts) { return Object.assign({ fn }, opts || {}); }

/** @typedef {{ id: string, name: string, n: number, s: number, kind: 'food'|'drink'|'buff', effects?: string[], draw: object }} Food2Entry */

/** effects: "EFFECT:seconds" or "EFFECT:seconds:amp" */
const ROSTER = [
  // --- ASIAN ---
  { id: 'food2_ramen_bowl', name: 'Ramen Bowl', n: 8, s: 0.8, kind: 'buff', effects: ['REGENERATION:10'], draw: W('bowl', { pal: 'yellow', garnish: 'leaf' }) },
  { id: 'food2_pho', name: 'Pho', n: 8, s: 0.8, kind: 'buff', effects: ['REGENERATION:12'], draw: W('bowl', { pal: 'cooked', garnish: 'leaf' }) },
  { id: 'food2_dumplings', name: 'Dumplings', n: 6, s: 0.6, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'green' }) },
  { id: 'food2_spring_roll', name: 'Spring Roll', n: 5, s: 0.5, kind: 'food', draw: W('taco', { pal: 'crust' }) },
  { id: 'food2_fried_rice', name: 'Fried Rice', n: 7, s: 0.7, kind: 'food', draw: W('bowl', { pal: 'yellow', garnish: 'orange' }) },
  { id: 'food2_teriyaki_chicken', name: 'Teriyaki Chicken', n: 8, s: 0.8, kind: 'buff', effects: ['STRENGTH:30'], draw: W('meat') },
  { id: 'food2_tempura', name: 'Tempura', n: 6, s: 0.6, kind: 'food', draw: W('bowl', { pal: 'crust', garnish: 'green' }) },
  { id: 'food2_miso_soup', name: 'Miso Soup', n: 5, s: 0.5, kind: 'buff', effects: ['REGENERATION:8'], draw: W('bowl', { pal: 'tan', garnish: 'green' }) },
  { id: 'food2_bibimbap', name: 'Bibimbap', n: 8, s: 0.8, kind: 'buff', effects: ['SPEED:40'], draw: W('bowl', { pal: 'red', garnish: 'green' }) },
  { id: 'food2_kimchi', name: 'Kimchi', n: 3, s: 0.3, kind: 'buff', effects: ['FIRE_RESISTANCE:20'], draw: W('bulb', { pal: 'red', crown: true }) },
  { id: 'food2_pork_bun', name: 'Pork Bun', n: 6, s: 0.6, kind: 'food', draw: W('bread') },
  { id: 'food2_udon', name: 'Udon', n: 7, s: 0.7, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'green' }) },
  { id: 'food2_yakitori', name: 'Yakitori', n: 6, s: 0.6, kind: 'food', draw: W('skewer', { pal: 'cooked' }) },
  { id: 'food2_sashimi', name: 'Sashimi', n: 5, s: 0.5, kind: 'buff', effects: ['WATER_BREATHING:30'], draw: W('sushi') },
  { id: 'food2_onigiri', name: 'Onigiri', n: 5, s: 0.5, kind: 'food', draw: W('onigiri') },
  { id: 'food2_curry_rice', name: 'Curry Rice', n: 8, s: 0.8, kind: 'buff', effects: ['RESISTANCE:30'], draw: W('bowl', { pal: 'orange', garnish: 'cream' }) },
  { id: 'food2_pad_thai', name: 'Pad Thai', n: 7, s: 0.7, kind: 'buff', effects: ['SPEED:35'], draw: W('bowl', { pal: 'orange', garnish: 'green' }) },
  { id: 'food2_green_curry', name: 'Green Curry', n: 8, s: 0.8, kind: 'buff', effects: ['FIRE_RESISTANCE:25'], draw: W('bowl', { pal: 'green', garnish: 'cream' }) },
  { id: 'food2_satay', name: 'Satay', n: 6, s: 0.6, kind: 'food', draw: W('skewer', { pal: 'cooked' }) },
  { id: 'food2_dal', name: 'Dal', n: 6, s: 0.6, kind: 'food', draw: W('bowl', { pal: 'orange', garnish: 'yellow' }) },
  { id: 'food2_naan', name: 'Naan', n: 5, s: 0.5, kind: 'food', draw: W('flatbread') },
  { id: 'food2_biryani', name: 'Biryani', n: 9, s: 0.9, kind: 'buff', effects: ['SATURATION:2'], draw: W('bowl', { pal: 'yellow', garnish: 'orange' }) },
  { id: 'food2_samosa', name: 'Samosa', n: 5, s: 0.5, kind: 'food', draw: W('empanada') },
  { id: 'food2_tandoori_chicken', name: 'Tandoori Chicken', n: 8, s: 0.8, kind: 'buff', effects: ['STRENGTH:35'], draw: W('meat') },
  { id: 'food2_dim_sum', name: 'Dim Sum', n: 6, s: 0.6, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'green' }) },
  { id: 'food2_congee', name: 'Congee', n: 6, s: 0.5, kind: 'buff', effects: ['REGENERATION:6'], draw: W('bowl', { pal: 'cream' }) },
  { id: 'food2_hot_pot', name: 'Hot Pot', n: 9, s: 0.9, kind: 'buff', effects: ['FIRE_RESISTANCE:20', 'REGENERATION:8'], draw: W('bowl', { pal: 'red', garnish: 'green' }) },
  { id: 'food2_mapo_tofu', name: 'Mapo Tofu', n: 7, s: 0.7, kind: 'buff', effects: ['FIRE_RESISTANCE:30'], draw: W('bowl', { pal: 'red', garnish: 'cream' }) },
  { id: 'food2_katsu', name: 'Katsu', n: 7, s: 0.7, kind: 'food', draw: W('steak') },
  { id: 'food2_takoyaki', name: 'Takoyaki', n: 5, s: 0.5, kind: 'food', draw: W('cluster', { pal: 'crust' }) },
  { id: 'food2_okonomiyaki', name: 'Okonomiyaki', n: 7, s: 0.7, kind: 'food', draw: W('pizza', { pal: 'yellow' }) },
  { id: 'food2_bao_burger', name: 'Bao Burger', n: 8, s: 0.8, kind: 'food', draw: W('burger') },
  { id: 'food2_laksa', name: 'Laksa', n: 8, s: 0.8, kind: 'buff', effects: ['WATER_BREATHING:35'], draw: W('bowl', { pal: 'orange', garnish: 'green' }) },
  { id: 'food2_nasi_lemak', name: 'Nasi Lemak', n: 8, s: 0.8, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'green' }) },
  { id: 'food2_banh_mi', name: 'Banh Mi', n: 7, s: 0.7, kind: 'buff', effects: ['SPEED:30'], draw: W('wrap') },

  // --- EUROPEAN ---
  { id: 'food2_paella', name: 'Paella', n: 9, s: 0.9, kind: 'food', draw: W('bowl', { pal: 'yellow', garnish: 'red' }) },
  { id: 'food2_ratatouille', name: 'Ratatouille', n: 6, s: 0.6, kind: 'buff', effects: ['SPEED:25'], draw: W('bowl', { pal: 'red', garnish: 'green' }) },
  { id: 'food2_quiche', name: 'Quiche', n: 6, s: 0.6, kind: 'food', draw: W('pie', { pal: 'yellow' }) },
  { id: 'food2_croissant', name: 'Croissant', n: 4, s: 0.4, kind: 'food', draw: W('croissant') },
  { id: 'food2_baguette', name: 'Baguette', n: 5, s: 0.5, kind: 'food', draw: W('baguette') },
  { id: 'food2_gnocchi', name: 'Gnocchi', n: 7, s: 0.7, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'green' }) },
  { id: 'food2_lasagna', name: 'Lasagna', n: 9, s: 0.9, kind: 'buff', effects: ['SATURATION:2'], draw: W('lasagna') },
  { id: 'food2_carbonara', name: 'Carbonara', n: 8, s: 0.8, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'yellow' }) },
  { id: 'food2_goulash', name: 'Goulash', n: 8, s: 0.8, kind: 'buff', effects: ['RESISTANCE:25'], draw: W('bowl', { pal: 'red', garnish: 'orange' }) },
  { id: 'food2_pierogi', name: 'Pierogi', n: 6, s: 0.6, kind: 'food', draw: W('empanada') },
  { id: 'food2_borscht', name: 'Borscht', n: 6, s: 0.6, kind: 'buff', effects: ['REGENERATION:8'], draw: W('bowl', { pal: 'red' }) },
  { id: 'food2_schnitzel', name: 'Schnitzel', n: 8, s: 0.8, kind: 'buff', effects: ['STRENGTH:30'], draw: W('steak') },
  { id: 'food2_bratwurst', name: 'Bratwurst', n: 7, s: 0.7, kind: 'food', draw: W('sausage') },
  { id: 'food2_fish_chips', name: 'Fish and Chips', n: 8, s: 0.8, kind: 'food', draw: W('fishChips') },
  { id: 'food2_shepherd_pie', name: "Shepherd's Pie", n: 9, s: 0.9, kind: 'food', draw: W('pie', { pal: 'cooked' }) },
  { id: 'food2_moussaka', name: 'Moussaka', n: 8, s: 0.8, kind: 'food', draw: W('lasagna') },
  { id: 'food2_spanakopita', name: 'Spanakopita', n: 6, s: 0.6, kind: 'food', draw: W('pie', { pal: 'green' }) },
  { id: 'food2_cottage_pie', name: 'Cottage Pie', n: 8, s: 0.8, kind: 'food', draw: W('pie', { pal: 'cooked' }) },
  { id: 'food2_welsh_rarebit', name: 'Welsh Rarebit', n: 6, s: 0.6, kind: 'buff', effects: ['HASTE:60'], draw: W('bread') },
  { id: 'food2_scotch_egg', name: 'Scotch Egg', n: 5, s: 0.5, kind: 'food', draw: W('bulb', { pal: 'crust' }) },
  { id: 'food2_beef_wellington', name: 'Beef Wellington', n: 10, s: 1.0, kind: 'buff', effects: ['STRENGTH:40', 'SATURATION:2'], draw: W('steak') },
  { id: 'food2_coq_au_vin', name: 'Coq au Vin', n: 9, s: 0.9, kind: 'buff', effects: ['REGENERATION:10'], draw: W('meat') },
  { id: 'food2_bouillabaisse', name: 'Bouillabaisse', n: 8, s: 0.8, kind: 'buff', effects: ['WATER_BREATHING:40'], draw: W('bowl', { pal: 'orange', garnish: 'red' }) },
  { id: 'food2_cassoulet', name: 'Cassoulet', n: 9, s: 0.9, kind: 'food', draw: W('bowl', { pal: 'cooked', garnish: 'cream' }) },
  { id: 'food2_souvlaki', name: 'Souvlaki', n: 7, s: 0.7, kind: 'food', draw: W('skewer', { pal: 'cooked' }) },
  { id: 'food2_tapas_platter', name: 'Tapas Platter', n: 7, s: 0.7, kind: 'food', draw: W('plate', { pal: 'red' }) },
  { id: 'food2_ribollita', name: 'Ribollita', n: 7, s: 0.7, kind: 'food', draw: W('bowl', { pal: 'green', garnish: 'cream' }) },
  { id: 'food2_cacciatore', name: 'Cacciatore', n: 8, s: 0.8, kind: 'buff', effects: ['NIGHT_VISION:120'], draw: W('bowl', { pal: 'red', garnish: 'green' }) },

  // --- MIDDLE EASTERN ---
  { id: 'food2_hummus', name: 'Hummus', n: 4, s: 0.4, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'green' }) },
  { id: 'food2_falafel', name: 'Falafel', n: 5, s: 0.5, kind: 'food', draw: W('cluster', { pal: 'green' }) },
  { id: 'food2_shawarma', name: 'Shawarma', n: 8, s: 0.8, kind: 'buff', effects: ['STRENGTH:30'], draw: W('wrap') },
  { id: 'food2_kebab', name: 'Kebab', n: 8, s: 0.8, kind: 'buff', effects: ['STRENGTH:35'], draw: W('skewer', { pal: 'cooked' }) },
  { id: 'food2_tabouleh', name: 'Tabouleh', n: 5, s: 0.5, kind: 'buff', effects: ['SPEED:30'], draw: W('salad') },
  { id: 'food2_baba_ganoush', name: 'Baba Ganoush', n: 4, s: 0.4, kind: 'food', draw: W('bowl', { pal: 'purple', garnish: 'green' }) },
  { id: 'food2_pita_bread', name: 'Pita Bread', n: 4, s: 0.4, kind: 'food', draw: W('flatbread') },
  { id: 'food2_lamb_tagine', name: 'Lamb Tagine', n: 9, s: 0.9, kind: 'buff', effects: ['REGENERATION:12'], draw: W('bowl', { pal: 'orange', garnish: 'green' }) },
  { id: 'food2_kofta', name: 'Kofta', n: 7, s: 0.7, kind: 'food', draw: W('cluster', { pal: 'cooked' }) },
  { id: 'food2_fattoush', name: 'Fattoush', n: 5, s: 0.5, kind: 'buff', effects: ['SPEED:25'], draw: W('salad') },
  { id: 'food2_mansaf', name: 'Mansaf', n: 10, s: 1.0, kind: 'buff', effects: ['SATURATION:3'], draw: W('bowl', { pal: 'cream', garnish: 'yellow' }) },
  { id: 'food2_kibbeh', name: 'Kibbeh', n: 6, s: 0.6, kind: 'food', draw: W('empanada') },
  { id: 'food2_mujadara', name: 'Mujadara', n: 7, s: 0.7, kind: 'food', draw: W('bowl', { pal: 'brown', garnish: 'green' }) },
  { id: 'food2_manakish', name: 'Manakish', n: 5, s: 0.5, kind: 'food', draw: W('flatbread') },
  { id: 'food2_stuffed_grape_leaves', name: 'Stuffed Grape Leaves', n: 5, s: 0.5, kind: 'food', draw: W('cluster', { pal: 'green' }) },
  { id: 'food2_shakshuka', name: 'Shakshuka', n: 7, s: 0.7, kind: 'buff', effects: ['FIRE_RESISTANCE:25'], draw: W('bowl', { pal: 'red', garnish: 'yellow' }) },
  { id: 'food2_ful_medames', name: 'Ful Medames', n: 6, s: 0.6, kind: 'food', draw: W('bowl', { pal: 'brown', garnish: 'green' }) },
  { id: 'food2_labneh', name: 'Labneh', n: 4, s: 0.4, kind: 'food', draw: W('bowl', { pal: 'cream' }) },
  { id: 'food2_persian_rice', name: 'Persian Rice', n: 7, s: 0.7, kind: 'buff', effects: ['NIGHT_VISION:180'], draw: W('bowl', { pal: 'yellow', garnish: 'orange' }) },
  { id: 'food2_turkish_delight', name: 'Turkish Delight', n: 3, s: 0.3, kind: 'food', draw: W('caramel') },
  { id: 'food2_pomegranate_seeds', name: 'Pomegranate Seeds', n: 3, s: 0.3, kind: 'buff', effects: ['REGENERATION:5'], draw: W('cluster', { pal: 'red' }) },
  { id: 'food2_tahini', name: 'Tahini', n: 3, s: 0.3, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'brown' }) },
  { id: 'food2_mehze_platter', name: 'Mezze Platter', n: 7, s: 0.7, kind: 'food', draw: W('plate', { pal: 'green' }) },
  { id: 'food2_harira', name: 'Harira', n: 7, s: 0.7, kind: 'buff', effects: ['REGENERATION:10'], draw: W('bowl', { pal: 'red', garnish: 'green' }) },
  { id: 'food2_manti', name: 'Manti', n: 6, s: 0.6, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'red' }) },

  // --- DESSERTS ---
  { id: 'food2_tiramisu', name: 'Tiramisu', n: 5, s: 0.5, kind: 'buff', effects: ['SPEED:50'], draw: W('slice', { pal: 'choco' }) },
  { id: 'food2_creme_brulee', name: 'Crème Brûlée', n: 5, s: 0.5, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'orange' }) },
  { id: 'food2_macaron', name: 'Macaron', n: 3, s: 0.3, kind: 'food', draw: W('cluster', { pal: 'pink' }) },
  { id: 'food2_baklava', name: 'Baklava', n: 5, s: 0.5, kind: 'buff', effects: ['HASTE:70'], draw: W('pie', { pal: 'yellow' }) },
  { id: 'food2_knafeh', name: 'Knafeh', n: 5, s: 0.5, kind: 'food', draw: W('pie', { pal: 'orange' }) },
  { id: 'food2_mochi', name: 'Mochi', n: 4, s: 0.4, kind: 'food', draw: W('cluster', { pal: 'pink' }) },
  { id: 'food2_flan', name: 'Flan', n: 4, s: 0.4, kind: 'food', draw: W('slice', { pal: 'orange' }) },
  { id: 'food2_pavlova', name: 'Pavlova', n: 5, s: 0.5, kind: 'food', draw: W('slice', { pal: 'cream' }) },
  { id: 'food2_cannoli', name: 'Cannoli', n: 4, s: 0.4, kind: 'food', draw: W('cannoli') },
  { id: 'food2_panna_cotta', name: 'Panna Cotta', n: 4, s: 0.4, kind: 'food', draw: W('slice', { pal: 'pink' }) },
  { id: 'food2_gelato', name: 'Gelato', n: 4, s: 0.5, kind: 'food', draw: W('iceCream', { pal: 'pink' }) },
  { id: 'food2_sorbet', name: 'Sorbet', n: 3, s: 0.3, kind: 'food', draw: W('iceCream', { pal: 'berry' }) },
  { id: 'food2_cupcake', name: 'Cupcake', n: 4, s: 0.4, kind: 'buff', effects: ['HASTE:60'], draw: W('cupcake') },
  { id: 'food2_brownie', name: 'Brownie', n: 4, s: 0.4, kind: 'food', draw: W('chocolate') },
  { id: 'food2_cheesecake', name: 'Cheesecake', n: 6, s: 0.6, kind: 'buff', effects: ['REGENERATION:8'], draw: W('slice', { pal: 'cream' }) },
  { id: 'food2_fudge', name: 'Fudge', n: 4, s: 0.4, kind: 'food', draw: W('chocolate') },
  { id: 'food2_truffle', name: 'Truffle', n: 3, s: 0.3, kind: 'buff', effects: ['SPEED:30'], draw: W('cluster', { pal: 'choco' }) },
  { id: 'food2_eclair', name: 'Éclair', n: 4, s: 0.4, kind: 'food', draw: W('eclair') },
  { id: 'food2_churros', name: 'Churros', n: 4, s: 0.4, kind: 'food', draw: W('churros') },
  { id: 'food2_sticky_toffee', name: 'Sticky Toffee Pudding', n: 6, s: 0.6, kind: 'buff', effects: ['REGENERATION:6'], draw: W('slice', { pal: 'brown' }) },
  { id: 'food2_banoffee_pie', name: 'Banoffee Pie', n: 6, s: 0.6, kind: 'food', draw: W('pie', { pal: 'brown' }) },
  { id: 'food2_pecan_pie', name: 'Pecan Pie', n: 6, s: 0.6, kind: 'food', draw: W('pie', { pal: 'brown' }) },
  { id: 'food2_lava_cake', name: 'Lava Cake', n: 5, s: 0.5, kind: 'buff', effects: ['FIRE_RESISTANCE:15'], draw: W('chocolate') },
  { id: 'food2_mille_feulle', name: 'Mille-Feuille', n: 5, s: 0.5, kind: 'food', draw: W('slice', { pal: 'cream' }) },
  { id: 'food2_pastry_assortment', name: 'Pastry Assortment', n: 5, s: 0.5, kind: 'food', draw: W('plate', { pal: 'crust' }) },

  // --- DRINKS ---
  { id: 'food2_bubble_tea', name: 'Bubble Tea', n: 3, s: 0.3, kind: 'drink', effects: ['SPEED:90'], draw: W('glass', { pal: 'brown', straw: 'pink', foam: true }) },
  { id: 'food2_matcha_latte', name: 'Matcha Latte', n: 2, s: 0.2, kind: 'drink', effects: ['HASTE:90'], draw: W('mug', { pal: 'green', topping: 'cream' }) },
  { id: 'food2_thai_iced_tea', name: 'Thai Iced Tea', n: 3, s: 0.3, kind: 'drink', draw: W('glass', { pal: 'orange', straw: 'cream' }) },
  { id: 'food2_horchata', name: 'Horchata', n: 3, s: 0.3, kind: 'drink', draw: W('glass', { pal: 'cream', straw: 'brown' }) },
  { id: 'food2_ayran', name: 'Ayran', n: 2, s: 0.2, kind: 'drink', draw: W('glass', { pal: 'cream' }) },
  { id: 'food2_mint_tea', name: 'Mint Tea', n: 2, s: 0.2, kind: 'drink', effects: ['SPEED:60'], draw: W('mug', { pal: 'green' }) },
  { id: 'food2_kombucha', name: 'Kombucha', n: 2, s: 0.2, kind: 'drink', effects: ['REGENERATION:8'], draw: W('glass', { pal: 'green' }) },
  { id: 'food2_ginger_ale', name: 'Ginger Ale', n: 2, s: 0.2, kind: 'drink', draw: W('glass', { pal: 'yellow' }) },
  { id: 'food2_coconut_water', name: 'Coconut Water', n: 3, s: 0.3, kind: 'drink', effects: ['WATER_BREATHING:30'], draw: W('glass', { pal: 'lime', straw: 'green' }) },
  { id: 'food2_sangria', name: 'Sangria', n: 3, s: 0.3, kind: 'drink', draw: W('glass', { pal: 'red', straw: 'orange' }) },
  { id: 'food2_cider', name: 'Cider', n: 3, s: 0.3, kind: 'drink', draw: W('glass', { pal: 'orange' }) },
  { id: 'food2_chai', name: 'Chai', n: 2, s: 0.2, kind: 'drink', effects: ['SPEED:90', 'HASTE:90'], draw: W('mug', { pal: 'brown', topping: 'cream' }) },
  { id: 'food2_oolong_tea', name: 'Oolong Tea', n: 1, s: 0.1, kind: 'drink', effects: ['NIGHT_VISION:120'], draw: W('mug', { pal: 'tan' }) },
  { id: 'food2_sake', name: 'Sake', n: 2, s: 0.2, kind: 'drink', draw: W('glass', { pal: 'cream' }) },
  { id: 'food2_egg_cream', name: 'Egg Cream', n: 3, s: 0.3, kind: 'drink', draw: W('glass', { pal: 'brown', foam: true }) },
  { id: 'food2_mango_lassi', name: 'Mango Lassi', n: 3, s: 0.4, kind: 'drink', effects: ['REGENERATION:6'], draw: W('glass', { pal: 'orange', foam: true }) },
  { id: 'food2_yuzu_ade', name: 'Yuzu Ade', n: 2, s: 0.2, kind: 'drink', draw: W('glass', { pal: 'lime' }) },
  { id: 'food2_rose_water', name: 'Rose Water', n: 2, s: 0.2, kind: 'drink', effects: ['REGENERATION:5'], draw: W('glass', { pal: 'pink' }) },
  { id: 'food2_turkish_coffee', name: 'Turkish Coffee', n: 1, s: 0.1, kind: 'drink', effects: ['SPEED:60', 'HASTE:60'], draw: W('mug', { pal: 'coffee' }) },
  { id: 'food2_iced_coffee', name: 'Iced Coffee', n: 2, s: 0.2, kind: 'drink', effects: ['SPEED:80'], draw: W('glass', { pal: 'coffee', straw: 'brown' }) },

  // --- STREET FOOD ---
  { id: 'food2_hot_dog', name: 'Hot Dog', n: 6, s: 0.6, kind: 'food', draw: W('hotDog') },
  { id: 'food2_soft_pretzel', name: 'Soft Pretzel', n: 5, s: 0.5, kind: 'food', draw: W('pretzel') },
  { id: 'food2_nachos', name: 'Nachos', n: 6, s: 0.6, kind: 'buff', effects: ['FIRE_RESISTANCE:15'], draw: W('nachos') },
  { id: 'food2_quesadilla', name: 'Quesadilla', n: 6, s: 0.6, kind: 'food', draw: W('quesadilla') },
  { id: 'food2_empanada', name: 'Empanada', n: 5, s: 0.5, kind: 'food', draw: W('empanada') },
  { id: 'food2_loaded_fries', name: 'Loaded Fries', n: 7, s: 0.7, kind: 'food', draw: W('fries') },
  { id: 'food2_corn_dog', name: 'Corn Dog', n: 6, s: 0.6, kind: 'food', draw: W('cornDog') },
  { id: 'food2_poutine', name: 'Poutine', n: 8, s: 0.8, kind: 'food', draw: W('bowl', { pal: 'cream', garnish: 'brown' }) },
  { id: 'food2_tacos_al_pastor', name: 'Tacos al Pastor', n: 7, s: 0.7, kind: 'buff', effects: ['FIRE_RESISTANCE:20'], draw: W('taco') },
  { id: 'food2_arepa', name: 'Arepa', n: 6, s: 0.6, kind: 'food', draw: W('arepa') },
  { id: 'food2_gyros_wrap', name: 'Gyros Wrap', n: 7, s: 0.7, kind: 'food', draw: W('wrap') },
  { id: 'food2_pretzel_dog', name: 'Pretzel Dog', n: 7, s: 0.7, kind: 'food', draw: W('hotDog') },
  { id: 'food2_street_corn', name: 'Street Corn', n: 5, s: 0.5, kind: 'buff', effects: ['FIRE_RESISTANCE:12'], draw: W('corn') },
  { id: 'food2_elote', name: 'Elote', n: 5, s: 0.5, kind: 'food', draw: W('corn') },
  { id: 'food2_jerk_skewer', name: 'Jerk Skewer', n: 6, s: 0.6, kind: 'buff', effects: ['STRENGTH:25'], draw: W('skewer', { pal: 'cooked' }) },

  // --- BUFF MEALS (hero-tier) ---
  { id: 'food2_feast_platter', name: 'Feast Platter', n: 12, s: 1.2, kind: 'buff', effects: ['STRENGTH:45', 'SATURATION:3'], draw: W('plate', { pal: 'cooked' }) },
  { id: 'food2_warrior_stew', name: 'Warrior Stew', n: 11, s: 1.1, kind: 'buff', effects: ['STRENGTH:40', 'RESISTANCE:30'], draw: W('bowl', { pal: 'red', garnish: 'cooked' }) },
  { id: 'food2_hunter_rations', name: 'Hunter Rations', n: 9, s: 0.9, kind: 'buff', effects: ['SPEED:60', 'NIGHT_VISION:180'], draw: W('plate', { pal: 'green' }) },
  { id: 'food2_miner_breakfast', name: "Miner's Breakfast", n: 10, s: 1.0, kind: 'buff', effects: ['HASTE:120', 'STRENGTH:30'], draw: W('plate', { pal: 'yellow' }) },
  { id: 'food2_hero_sandwich', name: 'Hero Sandwich', n: 10, s: 1.0, kind: 'buff', effects: ['STRENGTH:35', 'REGENERATION:10'], draw: W('heroSandwich') },
  { id: 'food2_phoenix_roast', name: 'Phoenix Roast', n: 11, s: 1.1, kind: 'buff', effects: ['FIRE_RESISTANCE:60', 'REGENERATION:12'], draw: W('meat') },
  { id: 'food2_dragon_noodles', name: 'Dragon Noodles', n: 10, s: 1.0, kind: 'buff', effects: ['STRENGTH:40', 'FIRE_RESISTANCE:30'], draw: W('bowl', { pal: 'red', garnish: 'yellow' }) },
  { id: 'food2_knight_feast', name: 'Knight Feast', n: 11, s: 1.1, kind: 'buff', effects: ['RESISTANCE:45', 'SATURATION:3'], draw: W('plate', { pal: 'cooked' }) },
  { id: 'food2_sea_kings_bounty', name: "Sea King's Bounty", n: 10, s: 1.0, kind: 'buff', effects: ['WATER_BREATHING:60', 'REGENERATION:10'], draw: W('bowl', { pal: 'orange', garnish: 'green' }) },
  { id: 'food2_golden_curry', name: 'Golden Curry', n: 11, s: 1.1, kind: 'buff', effects: ['STRENGTH:35', 'HASTE:60', 'SATURATION:2'], draw: W('bowl', { pal: 'yellow', garnish: 'orange' }) },
  { id: 'food2_elven_salad', name: 'Elven Salad', n: 8, s: 0.8, kind: 'buff', effects: ['SPEED:60', 'REGENERATION:8'], draw: W('salad') },
  { id: 'food2_diplomat_pastries', name: 'Diplomat Pastries', n: 7, s: 0.7, kind: 'buff', effects: ['HASTE:90', 'SPEED:30'], draw: W('plate', { pal: 'pink' }) },
];

module.exports = { ROSTER, W };
