package com.political.expansion2.melee;

/**
 * Self-contained RIGHT CLICK active abilities for expansion2 melee weapons ({@code wpn2_*}).
 */
public enum Melee2Ability {
    CURSED_SLASH("Domain Expansion Cut", "Unleash cursed energy in a cone ahead, afflicting foes.", 18, 6),
    CURSED_STAB("Cursed Energy Dagger", "Strike a foe with concentrated cursed force.", 20, 6),
    CURSED_CRUSH("Inverted Mace", "Erupt cursed power around you, hitting all nearby foes.", 28, 8),
    CURSED_REND("Black Flash Axe", "Unleash cursed energy in a cone ahead, afflicting foes.", 30, 8),
    CURSED_LUNGE("Shrine Spear", "Blink forward and deliver a cursed strike.", 43, 11),
    CURSED_REACH("Ten Shadows Halberd", "Unleash cursed energy in a cone ahead, afflicting foes.", 45, 11),
    CURSED_DRAW("Limitless Katana", "Unleash cursed energy in a cone ahead, afflicting foes.", 62, 15),
    CURSED_REAP("Malevolent Scythe", "Unleash cursed energy in a cone ahead, afflicting foes.", 64, 15),
    CURSED_SMASH("Shibuya Greatsword", "Erupt cursed power around you, hitting all nearby foes.", 86, 22),
    CURSED_CHOP("Jujutsu Cleaver", "Erupt cursed power around you, hitting all nearby foes.", 88, 22),
    CURSED_FRENZY("Grade One Claw", "Blink between nearby foes, cutting each with cursed fury.", 115, 30),
    CURSED_LASH("Special Grade Whip", "Unleash cursed energy in a cone ahead, afflicting foes.", 117, 30),
    PROM_SLASH("Radiant Cut", "Unleash prominence energy in a cone ahead.", 18, 6),
    PROM_STAB("Solar Dagger", "Strike a foe with concentrated prominence force.", 20, 6),
    PROM_CRUSH("Nova Mace", "Erupt prominence power around you, hitting all nearby foes.", 28, 8),
    PROM_REND("Ascendant Axe", "Unleash prominence energy in a cone ahead, afflicting foes.", 30, 8),
    PROM_LUNGE("Paragon Spear", "Blink forward and deliver a prominence strike.", 43, 11),
    PROM_REACH("Zenith Halberd", "Unleash prominence energy in a cone ahead, afflicting foes.", 45, 11),
    PROM_DRAW("Apex Katana", "Unleash prominence energy in a cone ahead.", 62, 15),
    PROM_REAP("Luminous Scythe", "Unleash prominence energy in a cone ahead, afflicting foes.", 64, 15),
    PROM_SMASH("Halcyon Greatsword", "Erupt prominence power around you, hitting all nearby foes.", 86, 22),
    PROM_CHOP("Empyrean Cleaver", "Erupt prominence power around you, hitting all nearby foes.", 88, 22),
    PROM_FRENZY("Transcendent Claw", "Blink between nearby foes, cutting each with prominence fury.", 115, 30),
    PROM_LASH("Apotheosis Whip", "Unleash prominence energy in a cone ahead.", 117, 30),
    ELEM_SLASH("Inferno Cut", "Unleash elemental energy in a cone ahead.", 18, 6),
    ELEM_STAB("Glacier Dagger", "Strike a foe with concentrated elemental force.", 20, 6),
    ELEM_CRUSH("Tempest Mace", "Erupt elemental power around you, hitting all nearby foes.", 28, 8),
    ELEM_REND("Tidal Axe", "Unleash elemental energy in a cone ahead, afflicting foes.", 30, 8),
    ELEM_LUNGE("Quake Spear", "Blink forward and deliver a elemental strike.", 43, 11),
    ELEM_REACH("Plasma Halberd", "Unleash elemental energy in a cone ahead, afflicting foes.", 45, 11),
    ELEM_DRAW("Magma Katana", "Unleash elemental energy in a cone ahead.", 62, 15),
    ELEM_REAP("Cryo Scythe", "Unleash elemental energy in a cone ahead, afflicting foes.", 64, 15),
    ELEM_SMASH("Storm Greatsword", "Erupt elemental power around you, hitting all nearby foes.", 86, 22),
    ELEM_CHOP("Ember Cleaver", "Erupt elemental power around you, hitting all nearby foes.", 88, 22),
    ELEM_FRENZY("Frostfire Claw", "Blink between nearby foes, cutting each with elemental fury.", 115, 30),
    ELEM_LASH("Cataclysm Whip", "Unleash elemental energy in a cone ahead, afflicting foes.", 117, 30),
    VOID_SLASH("Rift Cut", "Unleash void energy in a cone ahead.", 18, 6),
    VOID_STAB("Null Dagger", "Strike a foe with concentrated void force.", 20, 6),
    VOID_CRUSH("Oblivion Mace", "Erupt void power around you, hitting all nearby foes.", 28, 8),
    VOID_REND("Abyssal Axe", "Unleash void energy in a cone ahead, afflicting foes.", 30, 8),
    VOID_LUNGE("Event Horizon Spear", "Blink forward and deliver a void strike.", 43, 11),
    VOID_REACH("Entropy Halberd", "Unleash void energy in a cone ahead, afflicting foes.", 45, 11),
    VOID_DRAW("Annihilation Katana", "Unleash void energy in a cone ahead.", 62, 15),
    VOID_REAP("Singularity Scythe", "Unleash void energy in a cone ahead, afflicting foes.", 64, 15),
    VOID_SMASH("Eclipse Greatsword", "Erupt void power around you, hitting all nearby foes.", 86, 22),
    VOID_CHOP("Dark Matter Cleaver", "Erupt void power around you, hitting all nearby foes.", 88, 22),
    VOID_FRENZY("Phase Claw", "Blink between nearby foes, cutting each with void fury.", 115, 30),
    VOID_LASH("Unmaking Whip", "Unleash void energy in a cone ahead.", 117, 30),
    CEL_SLASH("Starfall Cut", "Unleash celestial energy in a cone ahead.", 18, 6),
    CEL_STAB("Nebula Dagger", "Strike a foe with concentrated celestial force.", 20, 6),
    CEL_CRUSH("Cosmic Mace", "Erupt celestial power around you, hitting all nearby foes.", 28, 8),
    CEL_REND("Aurora Axe", "Unleash celestial energy in a cone ahead, afflicting foes.", 30, 8),
    CEL_LUNGE("Supernova Spear", "Blink forward and deliver a celestial strike.", 43, 11),
    CEL_REACH("Orbit Halberd", "Unleash celestial energy in a cone ahead, afflicting foes.", 45, 11),
    CEL_DRAW("Pulsar Katana", "Unleash celestial energy in a cone ahead.", 62, 15),
    CEL_REAP("Quasar Scythe", "Unleash celestial energy in a cone ahead, afflicting foes.", 64, 15),
    CEL_SMASH("Lunar Greatsword", "Erupt celestial power around you, hitting all nearby foes.", 86, 22),
    CEL_CHOP("Solar Wind Cleaver", "Erupt celestial power around you, hitting all nearby foes.", 88, 22),
    CEL_FRENZY("Constellation Claw", "Blink between nearby foes, cutting each with celestial fury.", 115, 30),
    CEL_LASH("Divine Whip", "Unleash celestial energy in a cone ahead.", 117, 30),
    BLOOD_SLASH("Hemorrhage Cut", "Unleash blood energy in a cone ahead, afflicting foes.", 18, 6),
    BLOOD_STAB("Crimson Dagger", "Strike a foe with concentrated blood force.", 20, 6),
    BLOOD_CRUSH("Sanguine Mace", "Erupt blood power around you, hitting all nearby foes.", 28, 8),
    BLOOD_REND("Exsanguinate Axe", "Unleash blood energy in a cone ahead, afflicting foes.", 30, 8),
    BLOOD_LUNGE("Vitae Spear", "Blink forward and deliver a blood strike.", 43, 11),
    BLOOD_REACH("Carnage Halberd", "Unleash blood energy in a cone ahead, afflicting foes.", 45, 11),
    BLOOD_DRAW("Thirst Katana", "Unleash blood energy in a cone ahead, afflicting foes.", 62, 15),
    BLOOD_REAP("Coagulate Scythe", "Unleash blood energy in a cone ahead, afflicting foes.", 64, 15),
    BLOOD_SMASH("Arterial Greatsword", "Erupt blood power around you, hitting all nearby foes.", 86, 22),
    BLOOD_CHOP("Scarlet Cleaver", "Erupt blood power around you, hitting all nearby foes.", 88, 22),
    BLOOD_FRENZY("Transfusion Claw", "Blink between nearby foes, cutting each with blood fury.", 115, 30),
    BLOOD_LASH("Requiem Whip", "Unleash blood energy in a cone ahead, afflicting foes.", 117, 30),
    TECH_SLASH("Pulse Cut", "Unleash tech energy in a cone ahead.", 18, 6),
    TECH_STAB("Overclock Dagger", "Strike a foe with concentrated tech force.", 20, 6),
    TECH_CRUSH("Circuit Mace", "Erupt tech power around you, hitting all nearby foes.", 28, 8),
    TECH_REND("Ion Axe", "Unleash tech energy in a cone ahead, afflicting foes.", 30, 8),
    TECH_LUNGE("Plasma Spear", "Blink forward and deliver a tech strike.", 43, 11),
    TECH_REACH("Rail Halberd", "Unleash tech energy in a cone ahead, afflicting foes.", 45, 11),
    TECH_DRAW("Photon Katana", "Unleash tech energy in a cone ahead.", 62, 15),
    TECH_REAP("Quantum Scythe", "Unleash tech energy in a cone ahead, afflicting foes.", 64, 15),
    TECH_SMASH("Nano Greatsword", "Erupt tech power around you, hitting all nearby foes.", 86, 22),
    TECH_CHOP("Fusion Cleaver", "Erupt tech power around you, hitting all nearby foes.", 88, 22),
    TECH_FRENZY("Voltage Claw", "Blink between nearby foes, cutting each with tech fury.", 115, 30),
    TECH_LASH("Singularity Whip", "Unleash tech energy in a cone ahead.", 117, 30),
    NAT_SLASH("Thorn Cut", "Unleash nature energy in a cone ahead.", 18, 6),
    NAT_STAB("Bloom Dagger", "Strike a foe with concentrated nature force.", 20, 6),
    NAT_CRUSH("Root Mace", "Erupt nature power around you, hitting all nearby foes.", 28, 8),
    NAT_REND("Canopy Axe", "Unleash nature energy in a cone ahead, afflicting foes.", 30, 8),
    NAT_LUNGE("Spore Spear", "Blink forward and deliver a nature strike.", 43, 11),
    NAT_REACH("Pollen Halberd", "Unleash nature energy in a cone ahead, afflicting foes.", 45, 11),
    NAT_DRAW("Grove Katana", "Unleash nature energy in a cone ahead.", 62, 15),
    NAT_REAP("Wild Scythe", "Unleash nature energy in a cone ahead, afflicting foes.", 64, 15),
    NAT_SMASH("Feral Greatsword", "Erupt nature power around you, hitting all nearby foes.", 86, 22),
    NAT_CHOP("Moss Cleaver", "Erupt nature power around you, hitting all nearby foes.", 88, 22),
    NAT_FRENZY("Petal Claw", "Blink between nearby foes, cutting each with nature fury.", 115, 30),
    NAT_LASH("Overgrowth Whip", "Unleash nature energy in a cone ahead.", 117, 30),

    ;

    public final String displayName;
    public final String description;
    public final int manaCost;
    public final int cooldownSeconds;

    Melee2Ability(String displayName, String description, int manaCost, int cooldownSeconds) {
        this.displayName = displayName;
        this.description = description;
        this.manaCost = manaCost;
        this.cooldownSeconds = cooldownSeconds;
    }
}
